language: ruby
rvm:
- 2.1.2
deploy:
  provider: heroku
  api_key:
    secure: BBp0dRnLsIA3w6P/4L6qlUiXshQx+3TzJjIKzcR0sZgEgwxQHxtKfApWC23pNy7zlnMlNmJfS1Phljp3S8LCHUmz0PD7SLuuhQt6LFzJYGhAkAaRNPoL2bkwYoncuoGw33Fr2fqFJpmWm7wB4YoV+DBVGTx5G0JtODMHRbbSqxI=
  app: banter-world-cup
  on: master
#    repo: langphil/sweepstaker
