1:
  backer: Al
  status: In
2:
  backer: Amo
  status: In
3:
  backer: Amo 
  status: In
4:
  backer: Anneka
  status: In
5:
  backer: Billy Bury 
  status: In
6:
  backer: Brona 
  status: In
7:
  backer: Brona 
  status: In
8:
  backer: Bury
  status: In
9:
  backer: Bury 
  status: In
10:
  backer: Bury
  status: In
11:
  backer: Cathy
  status: In
12:
  backer: Davie 
  status: In
13:
  backer: Della 
  status: In
14:
  backer: Gav
  status: In
15:
  backer: Hego 
  status: In
16:
  backer: Hego 
  status: In
17:
  backer: Jamie 
  status: In
18:
  backer: Jamie 
  status: In
19:
  backer: Jamie 
  status: In
20:
  backer: Jim 
  status: In
21:
  backer: Ken 
  status: In
22:
  backer: Laura 
  status: In
23:
  backer: Laura
  status: In
24:
  backer: Mike 
  status: In
25:
  backer: Mike
  status: In
26:
  backer: Nyree
  status: In
27:
  backer: Nyree
  status: In
28:
  backer: Orla
  status: In
29:
  backer: Phil
  status: In
30:
  backer: Ro 
  status: In
31:
  backer: Paul
  status: In
32:
  backer: Paul 
  status: In
