Algeria:
  backer: Al
  status: In
Argentina:
  backer: Della
  status: In
Australia:
  backer: Jim
  status: Out
Belgium:
  backer: Bury
  status: In
Bosnia and Herzegovina:
  backer: Mike
  status: In
Brazil:
  backer: Hego
  status: In
Cameroon:
  backer: Orla
  status: Out
Chile:
  backer: Ken
  status: In
Colombia:
  backer: Laura
  status: In
Costa Rica:
  backer: Gav
  status: In
Croatia:
  backer: Bury
  status: In
Ecuador:
  backer: Billy Bury (Beast)
  status: In
England:
  backer: Laura
  status: In
France:
  backer: Ro
  status: In
Germany:
  backer: Davie
  status: In
Ghana:
  backer: Jamie
  status: In
Greece:
  backer: Cathy
  status: In
Honduras:
  backer: Jamie
  status: In
Iran:
  backer: Jamie
  status: In
Italy:
  backer: Hego
  status: In
Ivory Coast:
  backer: Bury
  status: In
Japan:
  backer: Mike
  status: In
Mexico:
  backer: Brona
  status: In
Netherlands:
  backer: Amo
  status: In
Nigeria:
  backer: Nyree
  status: In
Portugal:
  backer: Amo
  status: In
Russia:
  backer: Anneka
  status: In
South Korea:
  backer: Nyree
  status: In
Spain:
  backer: Brona
  status: Out
Switzerland:
  backer: Paul
  status: In
United States:
  backer: Phil
  status: In
Uruguay:
  backer: Paul
  status: In
