Algeria:
  backer: 
  status: In
Argentina:
  backer: 
  status: In
Australia:
  backer: 
  status: In
Belgium:
  backer: 
  status: In
Bosnia and Herzegovina:
  backer: 
  status: In
Brazil:
  backer: 
  status: In
Cameroon:
  backer: Orla Howard
  status: In
Chile:
  backer: 
  status: In
Colombia:
  backer: 
  status: In
Costa Rica:
  backer: 
  status: In
Croatia:
  backer: 
  status: In
Ecuador:
  backer: 
  status: In
England:
  backer: 
  status: In
France:
  backer: 
  status: In
Germany:
  backer: 
  status: In
Ghana:
  backer: 
  status: In
Greece:
  backer: 
  status: In
Honduras:
  backer: 
  status: In
Iran:
  backer: 
  status: In
Italy:
  backer: 
  status: In
Ivory Coast:
  backer: 
  status: In
Japan:
  backer: 
  status: In
Mexico:
  backer: 
  status: In
Netherlands:
  backer: 
  status: In
Nigeria:
  backer: 
  status: In
Portugal:
  backer: 
  status: In
Russia:
  backer: 
  status: In
South Korea:
  backer: 
  status: In
Spain:
  backer: 
  status: In
Switzerland:
  backer: 
  status: In
United States:
  backer: 
  status: In
Uruguay:
  backer: 
  status: In
